# Limite de block au delà de laquelle le joueur reçoit une alerte
# /!\ Seulement des entiers positifs /!\
BlockLimit: 100

# Liste des blocks pris en compte pour la détection
BlockList:
  - DIRT
  - GRASS_BLOCK
  - STONE

# Différents délai utiles au plugin (tous exprimés en seconde)
DelaySeconds:
  # Délai qui s'écoule entre 2 messages d'alerte
  DelayBetweenMessage: 30
  # Délai qu'il faut pour une remise à 0 du compteur
  DelayResetCounter: 180

# Liste des mondes pris en compte dans la détection
WorldList:
  - world
  - World2

Messages:
  Alert:
    Title : "Tu as miné beaucoup de blocs !"
    Subtitle: "Je te rappelle que tu es dans le monde "
  Bad-Arguments: "§9§l[§bPlugin§3Detection§9§l]§r §c→ La seule commande possible est /detection reload"
  Reload-Complete: "§9§l[§bPlugin§3Detection§9§l]§r §a→ reload effectué"
debug: false




