name: PluginDetection
version: '${project.version}'
main: fr.nono74210.plugindetection.PluginDetection
api-version: 1.19
authors: [ Nono74210 ]
description: Plugin de détection du monde pour avertir le joueur
commands:
  detection:
    description: Commande de base du plugin
    permission: detection.reload
    aliases:
      - pd
permissions:
  detection.bypass:
    description: Permet de bypass les alertes du plugin
  detection.reload:
    description: Permet de reload la config du plugin
    default: op
  detection.debug:
    description: Permet d'utiliser le debug du plugin si besoin
    default: op
depend:
  - Multiverse-Core

