name: PluginDetection
version: '${project.version}'
main: fr.nono74210.plugindetection.PluginDetection
api-version: 1.19
authors: [ Nono74210 ]
description: Plugin de détection du monde pour avertir le joueur
